"use client";
import { useEffect, useState, type FormEvent } from "react";
type State="idle"|"sending"|"sent"|"error";
type ContactSelection={package?:string;budget?:string;type?:string};

export function ContactSection(){
  const [state,setState]=useState<State>("idle");
  const [type,setType]=useState("");
  const [budget,setBudget]=useState("Not sure yet");
  const [packageName,setPackageName]=useState("");
  useEffect(()=>{const onSelection=(event:Event)=>{const detail=(event as CustomEvent<ContactSelection>).detail||{};if(detail.type)setType(detail.type);if(detail.budget)setBudget(detail.budget);if(detail.package)setPackageName(detail.package)};window.addEventListener("bizora:pricing",onSelection);window.addEventListener("bizora:interest",onSelection);return()=>{window.removeEventListener("bizora:pricing",onSelection);window.removeEventListener("bizora:interest",onSelection)}},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");const form=event.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!response.ok)throw new Error();setState("sent");form.reset();setType("");setBudget("Not sure yet");setPackageName("")}catch{setState("error")}}
  const status=state==="sent"?<>Thanks - your message is on its way.</>:state==="error"?<>Something went wrong. <a href="mailto:kaushik.rawalwork@gmail.com">Send to email directly</a>.</>:state==="sending"?<>Sending...</>:<>We reply as soon as we can.</>;
  return <section id="contact" className="section"><div className="content contact-grid"><div><div className="section-label">Start a project / 08</div><h2 className="contact-title">LET'S BUILD<br/><em>SOMETHING<br/>GREAT.</em></h2><p className="contact-copy">Tell us what you are trying to build, fix or launch. We'll come back with a clear next step.</p></div><form className="contact-form" onSubmit={submit}><input type="hidden" name="package" value={packageName}/><div className="field"><label htmlFor="name">Name</label><input id="name" name="name" required/></div><div className="field"><label htmlFor="business">Business</label><input id="business" name="business" required/></div><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required/></div><div className="field"><label htmlFor="website">Website</label><input id="website" name="website" placeholder="https://"/></div><div className="field"><label htmlFor="type">What do you want to build?</label><select id="type" name="type" value={type} onChange={event=>setType(event.target.value)} required><option value="">Select one</option><option>New Website</option><option>Website Redesign</option><option>E-commerce</option><option>Web Application</option><option>Other</option></select></div><div className="field"><label htmlFor="budget">Budget</label><select id="budget" name="budget" value={budget} onChange={event=>setBudget(event.target.value)}><option>Not sure yet</option><option>Under 5K</option><option>5K-10K</option><option>10K-25K</option><option>25K-50K</option><option>50K+</option></select></div><div className="field field--full"><label htmlFor="message">Message</label><textarea id="message" name="message" required placeholder="A sentence or two is enough."/></div><div className="form-actions"><div className="status" aria-live="polite">{status}</div><button className="btn btn--primary" disabled={state==="sending"}>{state==="sent"?"SENT":"SEND ENQUIRY"}</button></div></form></div></section>;
}
